// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools 2015 v1.7.160
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.TextGenerator
{
    static class Vsix
    {
        public const string Id = "0007e9e3-b11a-4d10-8565-9c6ce2ccc286";
        public const string Name = "Dummy Text Generator";
        public const string Description = "Easily insert dummy text into the editor in Visual Studio. Lorem Ipsum and other vocabularies are supported.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "lorum ipsum, strings";
    }
}
