// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9.179
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.TextGenerator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTextGeneratorPkgString = "0007e9e3-b11a-4d10-8565-9c6ce2ccc286";
        public const string guidTextGeneratorCmdSetString = "ea633062-6817-4827-a113-c839f5d878e7";
        public const string HtmlCmdSetString = "78f03954-2fb8-4087-8ce7-59d71710b3bb";
        public const string CssCmdSetString = "64da400e-b4ad-4d67-aa92-4b7acb01ecd5";
        public const string JsonCmdSetString = "f718ca06-cf4f-4a0c-9106-e79e9ee5e7cd";
        public const string guidImagesString = "f5ac8b23-8a65-4428-a41c-b7af2747066c";
        public static Guid guidTextGeneratorPkg = new Guid(guidTextGeneratorPkgString);
        public static Guid guidTextGeneratorCmdSet = new Guid(guidTextGeneratorCmdSetString);
        public static Guid HtmlCmdSet = new Guid(HtmlCmdSetString);
        public static Guid CssCmdSet = new Guid(CssCmdSetString);
        public static Guid JsonCmdSet = new Guid(JsonCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdGenerate = 0x0100;
        public const int htmlClipboard = 0x0064;
        public const int cssClipboard = 0x0064;
        public const int jsonClipboard = 0x0064;
        public const int abc = 0x0001;
    }
}
